# Original TpaGui plugin by ning-g-mo can be found on Modrinth at https://modrinth.com/plugin/tpagui and Github at https://github.com/RunicWonders/tpagui 
# English translation of plugin.yml for v1.1.0 by AnthonyKellyYip 
name: TpaGui
version: 1.1.0
main: cn.ningmo.tpagui.TpaGui
api-version: '1.21'
softdepend: [floodgate]

commands:
  tpagui:
    description: Opens TP Request GUI
    usage: "§cUsage: /<command>"
    aliases: [tpag, tgui]
    permission: tpagui.use
    permission-message: "§cYou do not have permission to use this command！"

permissions:
  tpagui.use:
    description: Allows use of /tpagui command
    default: true
  tpagui.admin:
    description: Administrator privileges (receive update notifications etc)
    default: op
